### ISSUE TITLE
使用red(NTQQ)适配器接入QQ时显示未知原因搜索失败

### ISSUE THREAD

**Issue by NaNaisNaNa** [koishijs/koishi-plugin-image-search#24]
由于未知原因搜索失败：Problem with remote server... (0 - http://127.0.0.1:5140/red_assets/66u28p/eyJtc2dJZCI6IjczMzEyMzM1NjY2MjA4MTMzNzMiLCJjaGF0VHlwZSI6MiwicGVlclVpZCI6IjY2MzE3MDkyNSIsImVsZW1lbnRJZCI6IjczMzEyMzM1NjY2MjA4MTMzNzIiLCJtaW1lIjoiaW1hZ2UvcG5nIiwibWQ1IjoiZGIyZjMzMGM2ZGMzODgzOWU2ZWVmYjliOGRmMzdhYTEifQ)
![image](https://github.com/koishijs/koishi-plugin-image-search/assets/111108719/f0761f1f-4294-415e-ad49-500665f03ea8)

**Comment by idranme** [comment]
#29 已解决该问题
