### ISSUE TITLE
koishi 4.17.2 下 ascii2d 搜索报错

### ISSUE THREAD

**Issue by Container-Zero** [koishijs/koishi-plugin-image-search#26]
koishi版本：`4.17.2`
所有依赖均已更新至最新

搜索ascii2d显示`访问失败。`，报错如下：
![Clipboard - 2024-03-09 15 40 17](https://github.com/koishijs/koishi-plugin-image-search/assets/20435019/38adaed4-f84b-473d-93b9-0bc17fb0b218)

**Comment by Container-Zero** [comment]
进一步测试，koishi在低版本`4.15.7`版本下，ascii2d可以正常运行，不会出错

**Comment by Neptune1990** [comment]
+1，等待大佬解决。
