### ISSUE TITLE
[Bug] QQ Url 方式搜图时部分链接可能会被阻止引用的问题

### ISSUE THREAD

**Issue by SummonHIM** [koishijs/koishi-plugin-image-search#30]
假设获取的链接为
```
http://gchat.qpic.cn/offpic_new/xxx//xxx-xxx-xxx/0?term=255&is_origin=1
```
搜索有可能会触发腾讯的非法引用图片，导致搜索结果不准确
![image](https://github.com/koishijs/koishi-plugin-image-search/assets/33192611/a5d4392b-567d-445b-8efa-e69fdd996608)

## 可能的解决方案
[Tsuk1ko/cq-picsearcher-bot/src/index.mjs#L973](https://github.com/Tsuk1ko/cq-picsearcher-bot/blob/master/src/index.mjs#L973)

上面那个链接存在`//`，转换成gchatpic_new链接可能会出现400错误。

**Comment by shigma** [comment]
这个解决了吗？

**Comment by SummonHIM** [comment]
莫名其妙就好了，然后忘记有这个issue了
