### ISSUE TITLE
Feature: add config to disable thumbnails

### ISSUE THREAD

**Issue by Treerevenge** [koishijs/koishi-plugin-image-search#7]
### Describe the problem related to the feature request

image-search搜图插件自主选择是否显示略缩图开关

### Describe the solution you'd like

在配置选项里面显示是否带有搜图结果的略缩图

### Additional context

搜图插件结果自带略缩图导致经常被恶意举报，希望能添加功能自主关闭

**Comment by shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/181069784-5e9959f7-8772-4ca8-965d-cb939c33bf20.png)

新版本增加了「输出设置」，可以将缩略图功能关闭。
