### ISSUE TITLE
在沙盒中搜索出问题，在QQ中只显示链接没有图片

### ISSUE THREAD

**Issue by NingHaiY** [koishijs/koishi-plugin-image-search#8]
022-12-10 20:23:23 [W] gocqhttp 转换CQ码 ({"type":"image","data":{"file":"https://img1.saucenao.com/res/pixiv/10312/103124668_p0_master1200.jpg?auth=hJaGPTWNSOM2GPY-uA96Hw&exp=1670961600"}}) 到MiraiGo Element时出现错误: Get "https://img1.saucenao.com/res/pixiv/10312/103124668_p0_master1200.jpg?auth=hJaGPTWNSOM2GPY-uA96Hw&exp=1670961600": read tcp [2409:8a55:c19:98e0:99ef:aa5b:c155:9a72]:50242->[2606:4700:20::681a:e8]:443: wsarecv: An existing connection was forcibly closed by the remote host. 将忽略本段CQ码.
![image](https://user-images.githubusercontent.com/116812337/206855481-ced69042-3509-4763-b59b-bf6816090c02.png)
![image](https://user-images.githubusercontent.com/116812337/206855499-464eaf78-37cb-44c1-bc8c-1746d49af570.png)
![V~~4 AEG5R$S19B6J4WO12R](https://user-images.githubusercontent.com/116812337/206855516-7c4dbea8-fe99-47b4-8e58-99b85ab0bc61.png)
![image](https://user-images.githubusercontent.com/116812337/206855562-f8578af6-dc70-4723-9487-22ecef8fa748.png)

**Comment by ilharp** [comment]
小伙伴你好\~ 该问题并非插件自身 bug 导致，插件使用的相关问题可以前往 [Koishi 用户群](https://koishi.chat/about/contact.html) 或 [Koishi 论坛](https://forum.koishi.xyz) 交流讨论哦\~

**Comment by ilharp** [comment]
可通过插件发送 b64 图片解决此问题。分配至 @shigma

**Comment by ilharp** [comment]
由 #9 继承。
